### ISSUE TITLE
Fix parsing of clash scores for PDB-Dev 62, 63

### ISSUE THREAD

**Issue by benmwebb** [salilab/IHMValidation#18]
`Execute.py` fails for PDB-Dev entries 62 and 63 with

```
Traceback (most recent call last):
  File "/IHMValidation/example/Execute.py", line 208, in <module>
    template_dict, molprobity_dict, exv_data = report.run_model_quality(
  File "/IHMValidation/example/../master/pyext/src/validation/Report.py", line 240, in run_model_quality
    clashscores, Template_Dict['tot'] = I_mp.clash_summary_table(
  File "/IHMValidation/example/../master/pyext/src/validation/molprobity.py", line 574, in clash_summary_table
    dict1 = self.orderclashdict(dict1)
  File "/IHMValidation/example/../master/pyext/src/validation/molprobity.py", line 584, in orderclashdict
    df = pd.DataFrame(modeldict)
  File "/root/miniforge/lib/python3.9/site-packages/pandas/core/frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/root/miniforge/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/root/miniforge/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 120, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/root/miniforge/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 674, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

Looks like for some reason the code is only finding clash scores for 20 models even though the PDB-Dev entry has 25. Either the parsing of the MolProbity output is deficient here, or there really are no clashes for some of the models (in which case empty lists likely need to be returned so that everything works).

**Comment by aozalevsky** [comment]
I narrowed down the issue to two places in the code:

https://github.com/salilab/IHMValidation/blob/9d767d1ad6fc669661ee39a56db9212ae5be751d/master/pyext/src/validation/__init__.py#L704-L706

limits the number of models in the intermediate cif file for molprobity

and 
https://github.com/salilab/IHMValidation/blob/9d767d1ad6fc669661ee39a56db9212ae5be751d/master/pyext/src/validation/molprobity.py#L26

limits the number of models to be processed for the report. 

fixes are obvious and with them applied both PDB-Dev 62 and 63 can be processed correctly. However, there are many entries with a large number of models:
![image](https://user-images.githubusercontent.com/578484/160722628-06a9ba70-9a15-4a63-9afa-31dd0c2dc97d.png)
with a PDB-Dev 44 having a record number of 283 models. With such a large number of models plots became unusable (both online and in the PDF):

![2022-03-30-013054_547x703_scrot](https://user-images.githubusercontent.com/578484/160722933-ea6ea159-cbaf-49bc-a513-0e9c27774a77.png)

Thus I'll have to update the plotting simultaneously with the removal of the 20 models cap. This will require some time.

**Comment by benmwebb** [comment]
Another option would be to keep the 20-model cap (although if you do, the report should probably say somewhere that it's only reporting on the first 20 models) but impose the same cap for clashes so you don't get the original mismatch. I think either would work - it's your call.

**Comment by aozalevsky** [comment]
So I looked at how it is implemented in the PDB. As example: 
https://www.rcsb.org/structure/4P3Q - X-ray structure(!) with 167 models
and the report has data for every model:
https://files.rcsb.org/pub/pdb/validation_reports/p3/4p3q/4p3q_full_validation.pdf 

Though it is definitely unnecessary and even detrimental during development and testing because of the long generation times. 

What do you think if I introduce the same 20 structures cap under the control of the environmental variable? By default, it would be in the "PRODUCTION" mode (so everyone who clones the repo will have the fully-working pipeline), and in the "DEVELOPMENT" mode it will use 20 cap and maybe several other settings, which reduces the quality of images and etc in favor of speed?

**Comment by benmwebb** [comment]
Right, makes sense to follow what is done in PDB. Totally up to you whether you want a production/development flag.
