### ISSUE TITLE
beta site indexing by google

### ISSUE THREAD

**Issue by aozalevsky** [salilab/IHMValidation#36]
Looks like google is able to index pages of the beta site. My guess is that this is unnecessary? 
![2022-04-07-184653_626x111_scrot](https://user-images.githubusercontent.com/578484/162256476-b2137f04-743f-43d1-90f8-232e520028e0.png)

**Comment by benmwebb** [comment]
I wouldn't worry about it - these pages aren't secret, after all - but when the site gets out of beta, it'll probably be a good idea to set a canonical URL on each page.

**Comment by aozalevsky** [comment]
Seems like it was fixed. I tested multiple search prompts and the beta site was never shown. 

![2024-02-21-163646_998x844_scrot](https://github.com/salilab/IHMValidation/assets/578484/8256bbcc-9ab3-43cf-9e07-4b114d3679f2)
