### ISSUE TITLE
Redundant paths definitions 

### ISSUE THREAD

**Issue by aozalevsky** [salilab/IHMValidation#60]
Paths for tools from the `molprobity` and `ATSAS` suites are explicitly defined through environment variables. I think this is redundant since there is a generic and OS-independent way of using the PATH environment variable. 

```
ATSAS="" 
Molprobity_ramalyze=""
Molprobity_molprobity=""
Molprobity_clashscore=""
Molprobity_rotalyze=""
wkhtmltopdf=""

```

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L65

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L81

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L97

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L112

Moreover, in case of ATSAS it's a little bit misleading, since only `datcmp` used and not the whole ATSAS package. 

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/sas.py#L345-L346

**Comment by aozalevsky** [comment]
@benmwebb What do you think about this?

**Comment by benmwebb** [comment]
Agreed 100%, just have the OS look for these binaries in `PATH`.
