### ISSUE TITLE
Create documentation for creation of the sif file for deployment

### ISSUE THREAD

**Issue by brindakv** [salilab/IHMValidation#70]
Provide documentation for how to create the `.sif` file in the deployment script: 
https://github.com/salilab/IHMValidation/blob/dev_2.0/docker/deploy.sh#L20

**Comment by aozalevsky** [comment]
Done with 24f0118 but due to the rolling release model of Molprobity we can't guarantee that the latest version of the pipeline will work with the freshly-rebuilt image. See #72  for details
